function on_game_start()
	RegisterScriptCallback("actor_on_item_use", on_actor_item_use)
	RegisterScriptCallback("anabiotic_callback_before_change_weather", anabiotic_callback_before_change_weather)
end

function on_actor_item_use(obj_item, obj_item_section)
	if(obj_item) then
		if ffx_table_utils.is_contains({"drug_psy_blockade", "drug_radioprotector", "drug_antidot"}, obj_item_section) then
			xr_logic.pstor_store( 
				db.actor, 
				s_obj:section_name() .. "_expiration",
				atmosfear.CTimeAddSec(game.get_game_time(), ffx_ltx_utils.cfg_get_float(obj_item_section, "boost_time", 0.0) * level.get_time_factor())
			)
		end
	end
end

function anabiotic_callback_before_change_weather()
	local m = psi_storm_manager.get_psi_storm_manager()
	if(m.started) then
		local tf = level.get_time_factor()
		local diff_sec = math.ceil(game.get_game_time():diffSec(m.inited_time)/tf)
			if(rnd>(m.psi_storm_duration-diff_sec)*tf/60) then
			m.time_forwarded = true
			m:finish()
		end
	end
end