--------------------------------------------------------------------------------
-- AtmosFear class and functions -----------------------------------------------
-- Made by Cromm Cruac ---------------------------------------------------------
-- for AtmosFear 3 -------------------------------------------------------------
-- 25.06.2011 ------------------------------------------------------------------
--------------------------------------------------------------------------------
local atmosfear = nil
default_settings = {
	"r2_dof_far 800",
	"r2_dof -0.400000,1.400000,500.000000",
	"r2_dof_enable on",
	"r2_dof_kernel 2.0",
	"r2_dof_sky 0.0",
	"r2_ls_bloom_fast off",
	"r2_sun_depth_far_scale 1.0",
	"r2_sun_depth_near_scale 1.0",
	"r2_sun_far 180.0",
	"r2_sun_lumscale 1.0",
	"r2_sun_lumscale_amb 0.1",
	"r2_sun_lumscale_hemi 0.6",
	"r2_sun_near 30.0",
	"r2_tonemap on",
	"r2_tonemap_adaptation 0.2",
	"r2_tonemap_amount 1.0",
	"r2_tonemap_lowlum 0.4",
	"r2_tonemap_middlegray 1.1",
}

function on_game_start()
	RegisterScriptCallback("actor_on_update", function () 
		local atm_mgr = get_atmosfear()
		if atm_mgr then
			atm_mgr:update()
		end
	end)
	
	RegisterScriptCallback("actor_on_save", function (packet)
		local atm_mgr = get_atmosfear()
		if atm_mgr then
			atm_mgr:save(packet)
		end
	end)
	
	RegisterScriptCallback("actor_on_load", function (reader)
		local atm_mgr = get_atmosfear()
		if atm_mgr then
			atm_mgr:load(reader)
		end
	end)
end


class "CAtmosFear"
function CAtmosFear:__init()
	self.aspectRatio = 1
	if(device().width/device().height>(1024/768+0.01)) then
		self.aspectRatio = 0.8
	end

	self.param_ini = get_cached_ini("atmosfear_parameters.ltx")
	self:loadDefaultParameters()
end

function CAtmosFear:initialize()
end

function CAtmosFear:update()
	if not db.actor then
		return
	end
	
	-- DRUG PROTECTIONS CHECK
	local g_time=CTimeToSec(game.get_game_time())
	
	local expiration = xr_logic.pstor_retrieve(db.actor,"drug_psy_blockade_expiration")
	if expiration~=nil then
		if g_time<expiration then
			self.drug_telepatic_protection = ffx_ltx_utils.cfg_get_float("drug_psy_blockade", "boost_telepat_protection", 0.0)
		else
			self.drug_telepatic_protection = nil
		end
	end
	
	expiration = xr_logic.pstor_retrieve(db.actor,"drug_radioprotector_expiration")
	if expiration~=nil then
		if g_time<expiration then
			self.drug_radiation_protection = ffx_ltx_utils.cfg_get_float("drug_radioprotector", "boost_radiation_protection", 0.0)
		else
			self.drug_radiation_protection = nil
		end
	end
	
	expiration = xr_logic.pstor_retrieve(db.actor,"drug_antidot_expiration")
	if expiration~=nil then
		if g_time<expiration then
			self.drug_chemical_burn_protection = ffx_ltx_utils.cfg_get_float("drug_antidot", "boost_chemburn_protection", 0.0)
		else
			self.drug_chemical_burn_protection = nil
		end
	end

end

function CAtmosFear:hit_power(power,hit_type)
	local hit_types={"burn", "shock", "chemical_burn", "radiation", "telepatic"}
	local suit_factors={10,1,5,33,10}
	local drug_factors={1,1,5,33,10}
	local artefact_factors={10,5,10,10,10}
	local suit_protection = db.actor:get_current_outfit_protection(hit_type) * suit_factors[hit_type+1]
	local helmet_protection = 0
	local helmet = db.actor:item_in_slot(12)
	
	if helmet ~= nil then
		helmet_protection = ffx_ltx_utils.cfg_get_float(helmet:section(), hit_types[hit_type + 1] .. "_protection", 0.0) * suit_factors[hit_type + 1]
	end
	
	local drug_protection = 0
	if hit_type == 2 and self.drug_chemical_burn_protection ~= nil then
		drug_protection=self.drug_chemical_burn_protection*drug_factors[hit_type+1]
	elseif hit_type == 3 and self.drug_radiation_protection ~= nil then
		drug_protection=self.drug_radiation_protection*drug_factors[hit_type+1]
	elseif hit_type == 4 and self.drug_telepatic_protection ~= nil then
		drug_protection=self.drug_telepatic_protection*drug_factors[hit_type+1]
	end
	
	protection = (suit_protection + helmet_protection + drug_protection)
	if protection > 1 then 
		protection = 1
	end
	
	hit_power=power*(1-protection)

	return hit_power
end

function CAtmosFear:save(packet)
	SetStorageVar("atmosfear_mgr", {
		opt_weather_balance_presets = self.opt_weather_balance_presets,
		opt_weather_length_presets = self.opt_weather_length_presets,
		opt_zaton_period_good = self.opt_zaton_period_good,
		opt_zaton_period_bad = self.opt_zaton_period_bad,
		opt_zaton_period_good_length = self.opt_zaton_period_good_length,
		opt_zaton_period_bad_length = self.opt_zaton_period_bad_length,
		opt_jupiter_period_good = self.opt_jupiter_period_good,
		opt_jupiter_period_bad = self.opt_jupiter_period_bad,
		opt_jupiter_period_good_length = self.opt_jupiter_period_good_length,
		opt_jupiter_period_bad_length = self.opt_jupiter_period_bad_length,
		opt_pripyat_period_good = self.opt_pripyat_period_good,
		opt_pripyat_period_bad = self.opt_pripyat_period_bad,
		opt_pripyat_period_good_length = self.opt_pripyat_period_good_length,
		opt_pripyat_period_bad_length = self.opt_pripyat_period_bad_length,
		opt_enable_blowout = self.opt_enable_blowout,
		opt_blowout_freq = self.opt_blowout_freq,
		opt_blowout_fate = self.opt_blowout_fate,
		opt_blowout_warning = self.opt_blowout_warning,
		opt_blowout_task = self.opt_blowout_task,
		opt_enable_fallout = self.opt_enable_fallout,
		opt_fallout_freq = self.opt_fallout_freq,
		opt_fallout_fate = self.opt_fallout_fate,
		opt_fallout_warning = self.opt_fallout_warning,
		opt_fallout_task = self.opt_fallout_task,
		opt_enable_psi_storm = self.opt_enable_psi_storm,
		opt_psi_storm_freq = self.opt_psi_storm_freq,
		opt_psi_storm_fate = self.opt_psi_storm_fate,
		opt_psi_storm_warning = self.opt_psi_storm_warning,
		opt_psi_storm_task = self.opt_psi_storm_task,
		opt_moon_phase = self.opt_moon_phase,
		opt_night_brightness = self.opt_night_brightness,
	})
end

function CAtmosFear:load(packet)
	local data = GetStorageVar("atmosfear_mgr", {})
	
	self.opt_weather_balance_presets = data.opt_weather_balance_presets
	self.opt_weather_length_presets = data.opt_weather_length_presets
	self.opt_zaton_period_good = data.opt_zaton_period_good
	self.opt_zaton_period_bad = data.opt_zaton_period_bad
	self.opt_zaton_period_good_length = data.opt_zaton_period_good_length
	self.opt_zaton_period_bad_length = data.opt_zaton_period_bad_length
	self.opt_jupiter_period_good = data.opt_jupiter_period_good
	self.opt_jupiter_period_bad = data.opt_jupiter_period_bad
	self.opt_jupiter_period_good_length = data.opt_jupiter_period_good_length
	self.opt_jupiter_period_bad_length = data.opt_jupiter_period_bad_length
	self.opt_pripyat_period_good = data.opt_pripyat_period_good
	self.opt_pripyat_period_bad = data.opt_pripyat_period_bad
	self.opt_pripyat_period_good_length = data.opt_pripyat_period_good_length
	self.opt_pripyat_period_bad_length = data.opt_pripyat_period_bad_length
	self.opt_enable_blowout = data.opt_enable_blowout
	self.opt_blowout_freq = data.opt_blowout_freq
	self.opt_blowout_fate = data.opt_blowout_fate
	self.opt_blowout_warning = data.opt_blowout_warning
	self.opt_blowout_task = data.opt_blowout_task
	self.opt_enable_fallout = data.opt_enable_fallout
	self.opt_fallout_freq = data.opt_fallout_freq
	self.opt_fallout_fate = data.opt_fallout_fate
	self.opt_fallout_warning = data.opt_fallout_warning
	self.opt_fallout_task = data.opt_fallout_task
	self.opt_enable_psi_storm = data.opt_enable_psi_storm
	self.opt_psi_storm_freq = data.opt_psi_storm_freq
	self.opt_psi_storm_fate = data.opt_psi_storm_fate
	self.opt_psi_storm_warning = data.opt_psi_storm_warning
	self.opt_psi_storm_task = data.opt_psi_storm_task
	self.opt_moon_phase = data.opt_moon_phase
	self.opt_night_brightness = data.opt_night_brightness
end

function CAtmosFear:loadDefaultParameters()
	local parameters = xr_s.parse_ini_section_to_array(self.param_ini,"atmosfear_default_parameters")
	self.opt_weather_balance_presets	= parameters["opt_weather_balance_presets"]
	self.opt_weather_length_presets		= parameters["opt_weather_length_presets"]

	self.opt_zaton_period_good			= parameters["opt_zaton_period_good"]
	self.opt_zaton_period_bad			= parameters["opt_zaton_period_bad"]
	self.opt_zaton_period_good_length	= tonumber(parameters["opt_zaton_period_good_length"])
	self.opt_zaton_period_bad_length	= tonumber(parameters["opt_zaton_period_bad_length"])
	self.opt_jupiter_period_good		= parameters["opt_jupiter_period_good"]
	self.opt_jupiter_period_bad			= parameters["opt_jupiter_period_bad"]
	self.opt_jupiter_period_good_length	= tonumber(parameters["opt_jupiter_period_good_length"])
	self.opt_jupiter_period_bad_length	= tonumber(parameters["opt_jupiter_period_bad_length"])
	self.opt_pripyat_period_good		= parameters["opt_pripyat_period_good"]
	self.opt_pripyat_period_bad			= parameters["opt_pripyat_period_bad"]
	self.opt_pripyat_period_good_length	= tonumber(parameters["opt_pripyat_period_good_length"])
	self.opt_pripyat_period_bad_length	= tonumber(parameters["opt_pripyat_period_bad_length"])

	self.opt_enable_blowout				= tonumber(parameters["opt_enable_blowout"])
	self.opt_blowout_freq				= tonumber(parameters["opt_blowout_freq"])
	self.opt_blowout_fate				= parameters["opt_blowout_fate"]
	self.opt_blowout_warning			= parameters["opt_blowout_warning"]
	self.opt_blowout_task				= parameters["opt_blowout_task"]
	self.opt_enable_fallout				= tonumber(parameters["opt_enable_fallout"])
	self.opt_fallout_freq				= tonumber(parameters["opt_fallout_freq"])
	self.opt_fallout_fate				= parameters["opt_fallout_fate"]
	self.opt_fallout_warning			= parameters["opt_fallout_warning"]
	self.opt_fallout_task				= parameters["opt_fallout_task"]
	self.opt_enable_psi_storm			= tonumber(parameters["opt_enable_psi_storm"])
	self.opt_psi_storm_freq				= tonumber(parameters["opt_psi_storm_freq"])
	self.opt_psi_storm_fate				= parameters["opt_psi_storm_fate"]
	self.opt_psi_storm_warning			= parameters["opt_psi_storm_warning"]
	self.opt_psi_storm_task				= parameters["opt_psi_storm_task"]

	self.opt_moon_phase					= parameters["opt_moon_phase"]
	self.opt_night_brightness			= parameters["opt_night_brightness"]
	
	self.god_mode						= str_to_bool(parameters["opt_god_mode"])
end

function CAtmosFear:loadDefaultConsoleSettings()
	local console=get_console()
	for k,v in pairs(default_settings) do
		console:execute(v)
	end
end

function str_to_bool(str)
	if str=="true" then
		return true
	elseif str=="false" then
		return false
	else
		return nil
	end
end

function CTimeToSec(ctime)
	local Y, M, D, h, m, s, ms = 0, 0, 0, 0, 0, 0, 0
	Y, M, D, h, m, s, ms = ctime:get(Y, M, D, h, m, s, ms)
	return D*24*60*60 + h*60*60 + m*60 + s
end	

function CTimeAddSec(ctime,sec)
	local Y, M, D, h, m, s, ms = 0, 0, 0, 0, 0, 0, 0
	Y, M, D, h, m, s, ms = ctime:get(Y, M, D, h, m, s, ms)
	return D*24*60*60 + h*60*60 + m*60 + s + sec
end	

function get_atmosfear()
	if atmosfear == nil then
		atmosfear = CAtmosFear()
	end
	return atmosfear
end

