
local game_loaded = false
local delayed_actions = {}
local idx = 0
local atmosfear_parameters_ini = nil
local game_maps_single_ini = nil
local atmosfear_default_parameters = {}
local atmosfear_option_names = {}
local atmosfear_configured_levels = {}
local atmosfear_weather_presets_list = {}
local moons = {
	{"8days",	"st_cap_moon_cycle_length_8"},
	{"28days", 	"st_cap_moon_cycle_length_28"},
	{"moon0", 	"st_cap_moon_phase_0"},
	{"moon1", 	"st_cap_moon_phase_1"},
	{"moon2", 	"st_cap_moon_phase_2"},
	{"moon3", 	"st_cap_moon_phase_3"},
	{"moon4", 	"st_cap_moon_phase_4"},
	{"moon5", 	"st_cap_moon_phase_5"},
	{"moon6", 	"st_cap_moon_phase_6"},
	{"moon7", 	"st_cap_moon_phase_7"},
}

function on_game_start()
	RegisterScriptCallback("on_game_present", function () 
		game_loaded = true
		for k, v in ipairs(delayed_actions) do
			if v[1] ~= nil then
				--SemiLog("-- begin call delayed action: " ..tostring(v[2]) .. " = " .. tostring(v[3]))
				v[1]()
				--SemiLog("-- end call delayed action: " ..tostring(v[2]) .. " = " .. tostring(v[3]))
				--SemiLog("  ")
			end
		end
		delayed_actions = {}
	end)

	SetOptionTitle("af3_opt_name__title") -- Задаём заголовок для вкладки опций
	SetOptionAddonName("af3_opt_name__addon") -- Задаём название аддона для вкладки опций
	SetOptionScriptVersion("3.0.0") -- Задаём версию скрипта для вкладки опций
	SetOptionAuthors("Cromm Cruac | IXRay Team") -- Задаём авторов аддона для вкладки опций
	SetOptionIcon("addons_icons\\ixray_atmosfear_3_addon_icon") -- Задаём путь до иконки вкладки опций

	RegisterScriptCallback("on_init_ixr_options", function (_ref)
		atmosfear_parameters_ini = get_cached_ini("atmosfear_parameters.ltx")
		game_maps_single_ini = get_cached_ini("game_maps_single.ltx")
		
		atmosfear_default_parameters = ffx_ltx_utils.parse_section_to_array(atmosfear_parameters_ini, "atmosfear_default_parameters")
		atmosfear_option_names = ffx_ltx_utils.parse_section_to_array(atmosfear_parameters_ini, "atmosfear_option_names")
		atmosfear_weather_presets_list = ffx_ltx_utils.parse_section_to_array(atmosfear_parameters_ini, "weather_presets_list")
		atmosfear_configured_levels = parse_atmosfear_configured_levels()
	
		local presets_variants_idx = {}
		local presets_variants = {}
		for i, preset_name in ipairs(ffx_table_utils.get_array_keys(atmosfear_weather_presets_list)) do
			table.insert(presets_variants, _ref.combo_box_item(get_translate_alias(preset_name), true, preset_name))
			table.insert(presets_variants_idx, preset_name)
		end

		for i, level_name in ipairs(atmosfear_configured_levels) do
			local good_preset_idx = ffx_table_utils.get_contains_element_number(presets_variants_idx, atmosfear_default_parameters["opt_"..tostring(level_name).."_period_good"] or "-none-")
			local bad_preset_idx = ffx_table_utils.get_contains_element_number(presets_variants_idx, atmosfear_default_parameters["opt_"..tostring(level_name).."_period_bad"] or "-none-")
			
			_ref.register_option("st_cap_af_" .. tostring(level_name), tostring(level_name).."_presets_good", "af3_opt_name_first_weather", _ref.combo_box(good_preset_idx or 1, presets_variants), function (group, name, value) 
				update_af3_period_or_length("opt_"..tostring(level_name).."_period_good", value)
			end)
			
			_ref.register_option("st_cap_af_" .. tostring(level_name), tostring(level_name).."_presets_bad", "af3_opt_name_second_weather", _ref.combo_box(bad_preset_idx or 1, presets_variants), function (group, name, value) 
				update_af3_period_or_length("opt_"..tostring(level_name).."_period_bad", value)
			end)

			_ref.register_option("st_cap_af_" .. tostring(level_name), tostring(level_name).."_presets_good_length", "af3_opt_name_first_weather_length", _ref.track_bar(atmosfear_default_parameters["opt_"..tostring(level_name).."_period_good_length"], 1.0, 12.0, 1.0, true), function (group, name, value) 
				update_af3_period_or_length("opt_"..tostring(level_name).."_period_good_length", value)
			end)
			
			_ref.register_option("st_cap_af_" .. tostring(level_name), tostring(level_name).."_presets_bad_length", "af3_opt_name_second_weather_length", _ref.track_bar(atmosfear_default_parameters["opt_"..tostring(level_name).."_period_bad_length"], 1.0, 12.0, 1.0, true), function (group, name, value) 
				update_af3_period_or_length("opt_"..tostring(level_name).."_period_bad_length", value)
			end)
		end
		
		add_surge_options(_ref, game.translate_string("af3_opt_name__blowout"), "blowout", "list_blowout_freq", "list_blowout_fate", "list_blowout_warning", "list_blowout_task", "opt_enable_blowout", "opt_blowout_freq")
		add_surge_options(_ref, game.translate_string("af3_opt_name__acidic"), "fallout", "list_fallout_freq", "list_fallout_fate", "list_fallout_warning", "list_fallout_task", "opt_enable_fallout", "opt_fallout_freq")
		add_surge_options(_ref, game.translate_string("af3_opt_name__psy"), "psi_storm", "list_psi_storm_freq", "list_psi_storm_fate", "list_psi_storm_warning", "list_psi_storm_task", "opt_enable_psi_storm", "opt_psi_storm_freq")
		
		local moon_variants_idx = {}
		local moon_variants = {}
		for i, data in ipairs(moons) do
			table.insert(moon_variants, _ref.combo_box_item(data[2], true, data[1]))
			table.insert(moon_variants_idx, data[1])
		end
		
		local moon_options_idx = ffx_table_utils.get_contains_element_number(moon_variants_idx, atmosfear_default_parameters["opt_moon_phase"])
		_ref.register_option(game.translate_string("af3_opt_name_night_params"), "moon_phase", game.translate_string("af3_opt_name__moon_phase"), _ref.combo_box(moon_options_idx or 1, moon_variants), function (group, name, value) 
			update_af3_moon_or_brightness("opt_moon_phase", value)
		end)
		
		local night_brightness_idx = {}
		local night_brightness_variants = {}
		for k, v in pairs(ffx_ltx_utils.parse_section_to_array(atmosfear_parameters_ini, "list_night_brightness")) do
			local value = ffx_string_utils.remove_substring(k, "list_night_brightness_")
			table.insert(night_brightness_variants, _ref.combo_box_item(get_translate_alias(value), true, value))
			table.insert(night_brightness_idx, value)
		end
		local night_brightness_options_idx = ffx_table_utils.get_contains_element_number(night_brightness_idx, atmosfear_default_parameters["opt_night_brightness"])
		_ref.register_option(game.translate_string("af3_opt_name_night_params"), "night_brightness", game.translate_string("af3_opt_name__night_brightness"), _ref.combo_box(night_brightness_options_idx or 1, night_brightness_variants), function (group, name, value) 
			update_af3_moon_or_brightness("opt_night_brightness", value)
		end)
		
	end)
end

function add_surge_options(_ref, group_name, prefix, freq_opt_name, fate_opt_name, warnings_opt_name, tasks_opt_name, enable_opt_name, opt_freq_name)
	_ref.register_option(group_name, prefix, group_name.." "..game.translate_string("af3_opt_name__on"), _ref.check_box(tostring(atmosfear_default_parameters[enable_opt_name])=="1"), function (group, name, value)
		update_af3_surges("opt_enable_"..prefix, value, prefix)
	end)
	
	local list_blowout_freq_options_idx = {}
	local list_blowout_freq_options = {}
	for k, v in pairs(ffx_ltx_utils.parse_section_to_array(atmosfear_parameters_ini, freq_opt_name)) do
		local value = ffx_string_utils.remove_substring(k, "list_freq_")
		table.insert(list_blowout_freq_options, _ref.combo_box_item(get_translate_alias(tostring(value)), true, value))
		table.insert(list_blowout_freq_options_idx, value)
	end
	
	local blowout_freq_options_idx = ffx_table_utils.get_contains_element_number(list_blowout_freq_options_idx, atmosfear_default_parameters[opt_freq_name])
	_ref.register_option(group_name, prefix.."_freq", game.translate_string("af3_opt_name__freq"), _ref.combo_box(blowout_freq_options_idx, list_blowout_freq_options), function (group, name, value) 
		update_af3_surges("opt_"..prefix.."_freq", value, prefix)
	end)
	
	local list_blowout_fate_options = {}
	for k, v in pairs(ffx_ltx_utils.parse_section_to_array(atmosfear_parameters_ini, fate_opt_name)) do
		table.insert(list_blowout_fate_options, _ref.combo_box_item("st_"..tostring(k), true, ffx_string_utils.remove_substring(k, "list_fate_")))
	end
	_ref.register_option(group_name, prefix.."_fate", game.translate_string("af3_opt_name__fate"), _ref.combo_box(1, list_blowout_fate_options), function (group, name, value) 
		update_af3_surges("opt_"..prefix.."_fate", value, "")
	end)
	
	local list_blowout_warning_options = {}
	for k, v in pairs(ffx_ltx_utils.parse_section_to_array(atmosfear_parameters_ini, warnings_opt_name)) do
		table.insert(list_blowout_warning_options, _ref.combo_box_item("st_"..tostring(k), true, ffx_string_utils.remove_substring(k, "list_warning_")))
	end
	_ref.register_option(group_name, prefix.."_warning", game.translate_string("af3_opt_name__warning"), _ref.combo_box(1, list_blowout_warning_options), function (group, name, value) 
		update_af3_surges("opt_"..prefix.."_warning", value, "")
	end)
	
	local list_fallout_task_options = {}
	for k, v in pairs(ffx_ltx_utils.parse_section_to_array(atmosfear_parameters_ini, tasks_opt_name)) do
		table.insert(list_fallout_task_options, _ref.combo_box_item("st_"..tostring(k), true, ffx_string_utils.remove_substring(k, "list_task_")))
	end
	_ref.register_option(group_name, prefix.."_task", game.translate_string("af3_opt_name__task"), _ref.combo_box(1, list_fallout_task_options), function (group, name, value) 
		update_af3_surges("opt_"..prefix.."_task", value, "")
	end)
end


function delayed_action(callable, option_name, option_value)
	if game_loaded then
		--SemiLog("forward call: " ..tostring(option_name) .. " = " .. tostring(option_value))
		callable()
	else
		--SemiLog("add to delay call: " ..tostring(option_name) .. " = " .. tostring(option_value))
		table.insert(delayed_actions, {callable, option_name, option_value})
	end
end

function update_af3_period_or_length(option_name, option_value)
	delayed_action(function ()
		local atm_mgr = atmosfear.get_atmosfear()
		if atm_mgr then
			local changed = atm_mgr[option_name] ~= option_value
			atm_mgr[option_name] = option_value
			if changed then
				--SemiLog("call :level_weathers.get_weather_manager():get_next_period_change_hour(level_weathers.get_weather_manager().period)")
				level_weathers.get_weather_manager():get_next_period_change_hour(level_weathers.get_weather_manager().period)
			end
		end
	end, option_name, option_value)
end

function update_af3_moon_or_brightness(option_name, option_value)
	delayed_action(function ()
		local atm_mgr = atmosfear.get_atmosfear()
		if atm_mgr then
			local changed = atm_mgr[option_name] ~= option_value
			atm_mgr[option_name] = option_value
			if changed then
				--SemiLog("call :level_weathers.get_weather_manager():select_weather(true)")
				level_weathers.get_weather_manager():select_weather(true)
			end
		end
	end, option_name, option_value)
end

function update_af3_surges(option_name, option_value, prefix)
	if upd_surge_mgr == nil then
		upd_surge_mgr = false
	end
	
	if upd_psi_mgr == nil then
		upd_psi_mgr = false
	end
	
	delayed_action(function ()
		local atm_mgr = atmosfear.get_atmosfear()
		if atm_mgr then
			local changed = atm_mgr[option_name] ~= option_value
			atm_mgr[option_name] = option_value
			if changed then
				if prefix == "blowout" then
					--SemiLog("call :surge_manager.get_surge_manager():new_surge_time(true)")
					surge_manager.get_surge_manager():new_surge_time(true)
				end
				if prefix == "psi_storm" then
					--SemiLog("call :psi_storm_manager.get_psi_storm_manager():new_psi_storm_time(true)")
					psi_storm_manager.get_psi_storm_manager():new_psi_storm_time(true)
				end
			end
		end
	end, option_name, option_value)
end

function get_translate_alias(str)
	for k, v in pairs(atmosfear_option_names) do
		if k == str then
			return v
		end
	end
	
	return str
end

function parse_atmosfear_configured_levels()
	local parsed_levels = {}
	local allowed_game_maps_single_levels = ffx_ltx_utils.parse_section_to_array(game_maps_single_ini, "level_maps_single")
	for atmosfear_parameter, v in pairs(atmosfear_default_parameters) do
		for lvl_name, vv in pairs(allowed_game_maps_single_levels) do
			if ffx_string_utils.contains(atmosfear_parameter, lvl_name) and ffx_compare_utils.has_pattern(atmosfear_parameter, "opt_*_period_good") then 
				parsed_levels[lvl_name] = true
			end
		end
	end
	
	return ffx_table_utils.get_array_keys(parsed_levels)
end